/* eslint-disable import/no-anonymous-default-export */
export default {
    GET_USERS_REQUEST:"GET_USERS_REQUEST",
    GET_USERS_SUCCESS:"GET_USERS_SUCCESS",
    GET_USERS_FAIL:"GET_USERS_FAIL",
    PUT_USERS_REQUEST:"PUT_USERS_REQUEST",
    PUT_USERS_SUCCESS:"PUT_USERS_SUCCESS",
    PUT_USERS_FAIL:"PUT_USERS_FAIL",
    DELETE_USERS_REQUEST: "DELETE_USERS_REQUEST",
    DELETE_USERS_SUCCESS: "DELETE_USERS_SUCCESS",
    DELETE_USERS_FAIL: "DELETE_USERS_FAIL",

    
    

}